name: isar
description: Fast Cross Platform Database for Flutter Apps. Supports indexes, FTS, queries etc.
version: 2.2.2
repository: https://github.com/robban112/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  js: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
  ffigen: ^3.0.0
  lints: ^1.0.1
